language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
    pip install -r requirements.txt
    pip install coveralls
script:
    python3 -m unittest discover tests/
    coverage run -m unittest discover tests/
after_success:
<<<<<<< HEAD
    coveralls
=======
    coveralls
>>>>>>> ec2272810bfd82481bb5e8713137b6c9a55d6bcd
