language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
install:
    pip install -r requirements.txt coveralls
script:
    - python3 -m unittest discover tests/
    - coverage run  --omit /home/travis/virtualenv/ --source ./tnsnames -m unittest discover tests/
after_success:
    coveralls
